version: '3.8'
services:
  app:
    image: monica
    ports:
      - 8085:80
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/database.sqlite
    volumes:
      - monica-data:/var/www/html/storage
    restart: always

volumes:
  monica-data:
    name: monica-data
    external: true